#!/usr/bin/env python3

# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.14.2
import sys
sys.path.insert(1, '../')
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from sudoku import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.field_2_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_0.setGeometry(QtCore.QRect(30, 120, 30, 30))
        self.field_2_0.setObjectName("field_2_0")
        self.field_3_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_0.setGeometry(QtCore.QRect(30, 180, 30, 30))
        self.field_3_0.setObjectName("field_3_0")
        self.field_4_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_0.setGeometry(QtCore.QRect(30, 220, 30, 30))
        self.field_4_0.setObjectName("field_4_0")
        self.field_5_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_0.setGeometry(QtCore.QRect(30, 260, 30, 30))
        self.field_5_0.setObjectName("field_5_0")
        self.field_6_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_0.setGeometry(QtCore.QRect(30, 320, 30, 30))
        self.field_6_0.setObjectName("field_6_0")
        self.field_7_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_0.setGeometry(QtCore.QRect(30, 360, 30, 30))
        self.field_7_0.setObjectName("field_7_0")
        self.field_8_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_0.setGeometry(QtCore.QRect(30, 400, 30, 30))
        self.field_8_0.setObjectName("field_8_0")
        self.field_1_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_0.setGeometry(QtCore.QRect(30, 80, 30, 30))
        self.field_1_0.setObjectName("field_1_0")
        self.field_0_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_1.setGeometry(QtCore.QRect(70, 40, 30, 30))
        self.field_0_1.setObjectName("field_0_1")
        self.field_2_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_1.setGeometry(QtCore.QRect(70, 120, 30, 30))
        self.field_2_1.setObjectName("field_2_1")
        self.field_3_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_1.setGeometry(QtCore.QRect(70, 180, 30, 30))
        self.field_3_1.setObjectName("field_3_1")
        self.field_1_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_1.setGeometry(QtCore.QRect(70, 80, 30, 30))
        self.field_1_1.setObjectName("field_1_1")
        self.field_4_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_1.setGeometry(QtCore.QRect(70, 220, 30, 30))
        self.field_4_1.setObjectName("field_4_1")
        self.field_6_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_1.setGeometry(QtCore.QRect(70, 320, 30, 30))
        self.field_6_1.setObjectName("field_6_1")
        self.field_7_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_1.setGeometry(QtCore.QRect(70, 360, 30, 30))
        self.field_7_1.setObjectName("field_7_1")
        self.field_8_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_1.setGeometry(QtCore.QRect(70, 400, 30, 30))
        self.field_8_1.setObjectName("field_8_1")
        self.field_5_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_1.setGeometry(QtCore.QRect(70, 260, 30, 30))
        self.field_5_1.setObjectName("field_5_1")
        self.field_0_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_2.setGeometry(QtCore.QRect(110, 40, 30, 30))
        self.field_0_2.setObjectName("field_0_2")
        self.field_2_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_2.setGeometry(QtCore.QRect(110, 120, 30, 30))
        self.field_2_2.setObjectName("field_2_2")
        self.field_3_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_2.setGeometry(QtCore.QRect(110, 180, 30, 30))
        self.field_3_2.setObjectName("field_3_2")
        self.field_1_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_2.setGeometry(QtCore.QRect(110, 80, 30, 30))
        self.field_1_2.setObjectName("field_1_2")
        self.field_4_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_2.setGeometry(QtCore.QRect(110, 220, 30, 30))
        self.field_4_2.setObjectName("field_4_2")
        self.field_6_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_2.setGeometry(QtCore.QRect(110, 320, 30, 30))
        self.field_6_2.setObjectName("field_6_2")
        self.field_7_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_2.setGeometry(QtCore.QRect(110, 360, 30, 30))
        self.field_7_2.setObjectName("field_7_2")
        self.field_8_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_2.setGeometry(QtCore.QRect(110, 400, 30, 30))
        self.field_8_2.setObjectName("field_8_2")
        self.field_5_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_2.setGeometry(QtCore.QRect(110, 260, 30, 30))
        self.field_5_2.setObjectName("field_5_2")
        self.field_0_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_3.setGeometry(QtCore.QRect(170, 40, 30, 30))
        self.field_0_3.setObjectName("field_0_3")
        self.field_2_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_3.setGeometry(QtCore.QRect(170, 120, 30, 30))
        self.field_2_3.setObjectName("field_2_3")
        self.field_3_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_3.setGeometry(QtCore.QRect(170, 180, 30, 30))
        self.field_3_3.setObjectName("field_3_3")
        self.field_1_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_3.setGeometry(QtCore.QRect(170, 80, 30, 30))
        self.field_1_3.setObjectName("field_1_3")
        self.field_4_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_3.setGeometry(QtCore.QRect(170, 220, 30, 30))
        self.field_4_3.setObjectName("field_4_3")
        self.field_6_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_3.setGeometry(QtCore.QRect(170, 320, 30, 30))
        self.field_6_3.setObjectName("field_6_3")
        self.field_7_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_3.setGeometry(QtCore.QRect(170, 360, 30, 30))
        self.field_7_3.setObjectName("field_7_3")
        self.field_8_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_3.setGeometry(QtCore.QRect(170, 400, 30, 30))
        self.field_8_3.setObjectName("field_8_3")
        self.field_5_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_3.setGeometry(QtCore.QRect(170, 260, 30, 30))
        self.field_5_3.setObjectName("field_5_3")
        self.field_0_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_4.setGeometry(QtCore.QRect(210, 40, 30, 30))
        self.field_0_4.setObjectName("field_0_4")
        self.field_2_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_4.setGeometry(QtCore.QRect(210, 120, 30, 30))
        self.field_2_4.setObjectName("field_2_4")
        self.field_3_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_4.setGeometry(QtCore.QRect(210, 180, 30, 30))
        self.field_3_4.setObjectName("field_3_4")
        self.field_1_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_4.setGeometry(QtCore.QRect(210, 80, 30, 30))
        self.field_1_4.setObjectName("field_1_4")
        self.field_4_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_4.setGeometry(QtCore.QRect(210, 220, 30, 30))
        self.field_4_4.setObjectName("field_4_4")
        self.field_6_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_4.setGeometry(QtCore.QRect(210, 320, 30, 30))
        self.field_6_4.setObjectName("field_6_4")
        self.field_7_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_4.setGeometry(QtCore.QRect(210, 360, 30, 30))
        self.field_7_4.setObjectName("field_7_4")
        self.field_8_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_4.setGeometry(QtCore.QRect(210, 400, 30, 30))
        self.field_8_4.setObjectName("field_8_4")
        self.field_5_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_4.setGeometry(QtCore.QRect(210, 260, 30, 30))
        self.field_5_4.setObjectName("field_5_4")
        self.field_0_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_5.setGeometry(QtCore.QRect(250, 40, 30, 30))
        self.field_0_5.setObjectName("field_0_5")
        self.field_2_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_5.setGeometry(QtCore.QRect(250, 120, 30, 30))
        self.field_2_5.setObjectName("field_2_5")
        self.field_3_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_5.setGeometry(QtCore.QRect(250, 180, 30, 30))
        self.field_3_5.setObjectName("field_3_5")
        self.field_1_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_5.setGeometry(QtCore.QRect(250, 80, 30, 30))
        self.field_1_5.setObjectName("field_1_5")
        self.field_4_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_5.setGeometry(QtCore.QRect(250, 220, 30, 30))
        self.field_4_5.setObjectName("field_4_5")
        self.field_6_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_5.setGeometry(QtCore.QRect(250, 320, 30, 30))
        self.field_6_5.setObjectName("field_6_5")
        self.field_7_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_5.setGeometry(QtCore.QRect(250, 360, 30, 30))
        self.field_7_5.setObjectName("field_7_5")
        self.field_8_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_5.setGeometry(QtCore.QRect(250, 400, 30, 30))
        self.field_8_5.setObjectName("field_8_5")
        self.field_5_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_5.setGeometry(QtCore.QRect(250, 260, 30, 30))
        self.field_5_5.setObjectName("field_5_5")
        self.field_4_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_6.setGeometry(QtCore.QRect(310, 220, 30, 30))
        self.field_4_6.setObjectName("field_4_6")
        self.field_0_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_6.setGeometry(QtCore.QRect(310, 40, 30, 30))
        self.field_0_6.setObjectName("field_0_6")
        self.field_8_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_6.setGeometry(QtCore.QRect(310, 400, 30, 30))
        self.field_8_6.setObjectName("field_8_6")
        self.field_5_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_6.setGeometry(QtCore.QRect(310, 260, 30, 30))
        self.field_5_6.setObjectName("field_5_6")
        self.field_6_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_6.setGeometry(QtCore.QRect(310, 320, 30, 30))
        self.field_6_6.setObjectName("field_6_6")
        self.field_3_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_6.setGeometry(QtCore.QRect(310, 180, 30, 30))
        self.field_3_6.setObjectName("field_3_6")
        self.field_7_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_6.setGeometry(QtCore.QRect(310, 360, 30, 30))
        self.field_7_6.setObjectName("field_7_6")
        self.field_8_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_7.setGeometry(QtCore.QRect(350, 400, 30, 30))
        self.field_8_7.setObjectName("field_8_7")
        self.field_4_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_7.setGeometry(QtCore.QRect(350, 220, 30, 30))
        self.field_4_7.setObjectName("field_4_7")
        self.field_6_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_7.setGeometry(QtCore.QRect(350, 320, 30, 30))
        self.field_6_7.setObjectName("field_6_7")
        self.field_5_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_7.setGeometry(QtCore.QRect(350, 260, 30, 30))
        self.field_5_7.setObjectName("field_5_7")
        self.field_5_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_5_8.setGeometry(QtCore.QRect(390, 260, 30, 30))
        self.field_5_8.setObjectName("field_5_8")
        self.field_0_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_7.setGeometry(QtCore.QRect(350, 40, 30, 30))
        self.field_0_7.setObjectName("field_0_7")
        self.field_2_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_6.setGeometry(QtCore.QRect(310, 120, 30, 30))
        self.field_2_6.setObjectName("field_2_6")
        self.field_2_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_7.setGeometry(QtCore.QRect(350, 120, 30, 30))
        self.field_2_7.setObjectName("field_2_7")
        self.field_7_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_7.setGeometry(QtCore.QRect(350, 360, 30, 30))
        self.field_7_7.setObjectName("field_7_7")
        self.field_6_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_6_8.setGeometry(QtCore.QRect(390, 320, 30, 30))
        self.field_6_8.setObjectName("field_6_8")
        self.field_1_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_6.setGeometry(QtCore.QRect(310, 80, 30, 30))
        self.field_1_6.setObjectName("field_1_6")
        self.field_1_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_7.setGeometry(QtCore.QRect(350, 80, 30, 30))
        self.field_1_7.setObjectName("field_1_7")
        self.field_2_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_2_8.setGeometry(QtCore.QRect(390, 120, 30, 30))
        self.field_2_8.setObjectName("field_2_8")
        self.field_8_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_8_8.setGeometry(QtCore.QRect(390, 400, 30, 30))
        self.field_8_8.setObjectName("field_8_8")
        self.field_7_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_7_8.setGeometry(QtCore.QRect(390, 360, 30, 30))
        self.field_7_8.setObjectName("field_7_8")
        self.field_3_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_7.setGeometry(QtCore.QRect(350, 180, 30, 30))
        self.field_3_7.setObjectName("field_3_7")
        self.field_1_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_1_8.setGeometry(QtCore.QRect(390, 80, 30, 30))
        self.field_1_8.setObjectName("field_1_8")
        self.field_3_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_3_8.setGeometry(QtCore.QRect(390, 180, 30, 30))
        self.field_3_8.setObjectName("field_3_8")
        self.field_0_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_8.setGeometry(QtCore.QRect(390, 40, 30, 30))
        self.field_0_8.setObjectName("field_0_8")
        self.field_4_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_4_8.setGeometry(QtCore.QRect(390, 220, 30, 30))
        self.field_4_8.setObjectName("field_4_8")
        self.solveButton = QtWidgets.QPushButton(self.centralwidget)
        self.solveButton.setGeometry(QtCore.QRect(138, 450, 71, 25))
        self.solveButton.setObjectName("solveButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(27, 155, 391, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 295, 391, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(145, 40, 20, 391))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(285, 40, 20, 391))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.label_uns = QtWidgets.QLabel(self.centralwidget)
        self.label_uns.setGeometry(QtCore.QRect(106, 490, 241, 20))
        self.label_uns.setText("")
        self.label_uns.setAlignment(QtCore.Qt.AlignCenter)
        self.label_uns.setObjectName("label_uns")
        self.field_0_0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.field_0_0.setGeometry(QtCore.QRect(30, 40, 30, 30))
        self.field_0_0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.field_0_0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.field_0_0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.field_0_0.setPlaceholderText("")
        self.field_0_0.setObjectName("field_0_0")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(240, 450, 71, 25))
        self.clearButton.setObjectName("clearButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_board(self):
        board = np.zeros((9,9), 'int')
        for i in range(9):
            for j in range(9):
                program = 'global text; text = self.field_' + str(i) + '_' + str(j) +'.toPlainText()'
                exec(program)
                if text:
                    board[i][j] = int(text)
        return board

    def fill_board(self,board):
        for i in range(9):
            for j in range(9):
                program = 'self.field_' + str(i) + '_' + str(j) +'.setPlainText(str(' + str(board[i,j]) + '))'
                exec(program)

    def solve_button(self):
        board = self.get_board()
        my_sudoku = sudoku(board)
        solvable = my_sudoku.solve(verbose=0)
        if solvable: self.fill_board(my_sudoku.board)
        else: self.label_uns.setText('This Sudoku is not solvable!')

    def clear_button(self):
        for i in range(9):
            for j in range(9):
                program = 'self.field_' + str(i) + '_' + str(j) +".setPlainText('')"
                exec(program)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku Solver"))
        self.solveButton.setText(_translate("MainWindow", "Solve!"))
        self.clearButton.setText(_translate("MainWindow", "Clear!"))

        self.solveButton.clicked.connect(self.solve_button)
        self.clearButton.clicked.connect(self.clear_button)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
